selenium-hub:
  image: selenium/hub
  ports:
  - 4446:4444

chrome:
  image: selenium/node-chrome-debug
  links:
  - selenium-hub:hub
  ports:
  - 5900
  environment:
     NODE_MAX_INSTANCES: 1
     NODE_MAX_SESSION: 1
     HUB_PORT_4446_TCP_ADDR: hub
  volumes:
  - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
